# Github Workflow for CISS Scan
name: "IaCScanCheck"

jobs:
  SecurityCheck:
    needs: TerraformPlan
    runs-on: 
        group: cvs-linux-self-hosted
    container:
        image: quay-registry.aetna.com/expresscloud/rhl9-x86_64-kics-snyk-opa:latest
        credentials:
          username: ${{secrets.QUAY_BOT_USERNAME}}
          password: ${{secrets.QUAY_BOT_PASSWORD}}
    steps:
        - uses: actions/download-artifact@v3
          with: 
            name: expressplan-${{ github.sha }}
            path: /scan/tfutECE_Managed_Envs/
        - name: Run Tests
          continue-on-error: true
          run: |
            /apps/bin/iac_srv.sh
          env:
            PIPELINE_NM: ECS
            APP_NM: ${{ github.head_ref || github.ref_name }}
            SCAN_VERBOSE_LEVEL: ERR
            SCAN_RULE_SEVERITY: HIGH