pipeline{
    agent{
        node('CSS-CSE-AZURE')
    }
    
    parameters{
        string(name: 'Branch',defaultValue: 'main', description: 'Github default branch')
    }
    environment{
        PIPELINE_NM = 'CSE'
        APP_NM = 'CSE_TESTPIPELINE'
        SCAN_VERBOSE_LEVEL = 'ERR'
        SCAN_RULE_SEVERITY = 'HIGH'
    }
    stages{

        stage('Clean workspace'){
            steps{
                deleteDir()
            }
        }
        
        stage('Checkout') {
            steps {
                script {
                    def branch = params.Branch
                    echo "Github branch is ${branch}"
                    checkout ([$class: 'GitSCM', 
                    branches: [[name: "${branch}"]],
                    userRemoteConfigs: [[credentialsId: 'github', url: "https://github.aetna.com/CloudSecurityservice/CSE-IaC-Scanning.git"]]]
                    )
                }
            }
        }

        stage('Create Scan Directory and copy tfplan'){
            steps{
                script{
                    sh 'mkdir -p scan/tfutcsetest'
                    def workspaceDir = pwd()
                    echo"Workspce Directory: ${workspaceDir}"
                    sh "ls -R ${workspaceDir}"
                    def sourcetfpFilePath = "${workspaceDir}/tfplantest/*.json"
                    def targettfpFilePath = "${workspaceDir}/scan/tfutcsetest/"
                    sh "cp -r ${sourcetfpFilePath} ${targettfpFilePath}"
                    sh "ls -R ${targettfpFilePath}"
                    def sourceenvFilePath = "${workspaceDir}/tfplantest/.env"
                    sh "cp ${sourceenvFilePath} ${workspaceDir}"
                    sh "ls -R ${workspaceDir}"
                    
                }
            }
        }
        stage('Scan'){
            steps{
                script{
                    sh '''
                       echo "Running Integration Testing by scanning tfplan file"
                       docker pull paulchak/rhl9-x86_64-kics-snyk-opa:V25
                    '''
                    sh '''    
                        docker run -w /apps/bin --rm --name csetestcontainer -v ${WORKSPACE}:/workspace paulchak/rhl9-x86_64-kics-snyk-opa:V25 /bin/sh -c "/apps/bin/iac_srv.sh"
                    '''
                }
            }
        }
    }
}