


         CSE_GCP_RULES_HASH["CSE-PC-GCP-ARTIFACT-21822"]="2.18.2.2|2.18.2|artifact_registry_is_not_using_cmek|high|Data Protection|custom|gcp|All Artifact registries MUST use CVSH standard CMEK|ARTIFACT_REGISTRY|CSE-PC-GCP-ARTIFACT-21822|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository#kms_key_name"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-ARTIFACT-21824"]="2.18.2.4|2.18.2|artifact_registry_is_not_in_allowed_locations|high|Data Protection|custom|gcp|Encryption at-rest: All Artifact registries MUST use CVSH allowed resource locations|ARTIFACT_REGISTRY|CSE-PC-GCP-ARTIFACT-21824|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository#location"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-SECRETMANAGER-22121"]="2.21.2.1|2.21.2|secret_manager_is_not_using_cmek|high|Data Protection|custom|gcp|All Secret Manager MUST use CVSH standard CMEK|SECRET_MANAGER|CSE-PC-GCP-SECRETMANAGER-22121|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#kms_key_name"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-SECRETMANAGER-22154"]="2.21.5.4|2.21.5|secret_manager_is_not_in_allowed_locations|high|Governance|custom|gcp|All Secret Manager MUST use CVSH allowed resource locations|SECRET_MANAGER|CSE-PC-GCP-SECRETMANAGER-22154|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#location"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDRUNSVC-23314"]="2.33.1.4|2.33.1|cloudrun_service_is_using_default_service_account|high|IAM|custom|gcp|Default service account shall not be used(cloudrun service)|CLOUDRUN_SVC|CSE-PC-GCP-CLOUDRUNSVC-23314|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#service_account"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDRUNJOB-23319"]="2.33.1.9|2.33.1|cloudrun_job_is_using_default_service_account|high|IAM|custom|gcp|Default service account shall not be used(cloudrun job)|CLOUDRUN_SVC|CSE-PC-GCP-CLOUDRUNJOB-23319|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#service_account"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDRUNSVC-23322"]="2.33.2.2|2.33.2|cloudrun_service_is_not_using_cmek|high|Data Protection|custom|gcp|Cloud Run Service must use CVSH Standard CMEK|CLOUDRUN_JOB|CSE-PC-GCP-CLOUDRUNSVC-23322|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#encryption_key"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDRUNJOB-23323"]="2.33.2.3|2.33.2|cloudrun_job_is_not_using_cmek|high|Data Protection|custom|gcp|Cloud Run Job must use CVSH Standard CMEK|CLOUDRUN_JOB|CSE-PC-GCP-CLOUDRUNJOB-23323|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#encryption_key"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDRUNSVC-23352"]="2.33.5.2|2.33.5|cloudrun_service_deployed_in_unapproved_locations|high|Governance|custom|gcp|Ensure cloudrun service is deployed in valid approved locations|CLOUDRUN_SVC|CSE-PC-GCP-CLOUDRUNSVC-23352|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#location"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDRUNJOB-23353"]="2.33.5.3|2.33.5|cloudrun_job_deployed_in_unapproved_locations|high|Governance|custom|gcp|Ensure cloudrun jobs are deployed in valid approved location|CLOUDRUN_JOB|CSE-PC-GCP-CLOUDRUNJOB-23353|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#location"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-BIGTABLE-24421"]="2.44.2.1|2.44.2|bigtable_instance_is_not_encrypted_with_CMEK|medium|Data Protection|custom|gcp|CMEK required on all instances for data-at-rest|BIGTABLE|CSE-PC-GCP-BIGTABLE-24421|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance#kms_key_name"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDSQLSERVER-28121"]="2.81.2.1|2.81.2|cloud_sqlserver_instance_is_not_using_cmek_to_encrypt_data_at_rest|high|Data Protection|custom|gcp|CMEK required on all instances for data-at-rest|CLOUD_SQLSERVER|CSE-PC-GCP-CLOUDSQLSERVER-28121|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#encryption_key_name"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDSQLSERVER-28124"]="2.81.2.4|2.81.2|cloud_sqlserver_instance_is_not_configured_with_ssl_for_connections|high|Data Protection|custom|gcp|Instances must be configured to required SSL-TLS 1.2 for all connections|CLOUD_SQLSERVER|CSE-PC-GCP-CLOUDSQLSERVER-28124|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#ssl_mode"
         CSE_GCP_RULES_HASH["CSE-PC-GCP-CLOUDSQLSERVER-28133"]="2.81.3.3|2.81.3|cloud_sqlserver_private_access_is_not_configured_to_work_within_vpc|high|Network Security|custom|gcp|Google Private Service Access must be configured to allow private instance to work within the VPC|CLOUD_SQLSERVER|CSE-PC-GCP-CLOUDSQLSERVER-28133|https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#private_network"
