#!/usr/bin/env sh


             declare -A CSE_AZURE_RULES_HASH


#CSE_AZURE_RULES_HASH -Start  ---- Generated Code Don't Modify

             CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SERVICEBUS-13114"]="1.31.1.4|1.31.1|service_bus_namespace_have_local_auth_enabled|high|IAM Protection|custom|azure|Azure Service Bus must have local auth disabled|SERVICE_BUS|CSE-PC-AZURE-SERVICEBUS-13114|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SERVICEBUS-13121"]="1.31.2.1|1.31.2|service_bus_namespace_is_not_using_cmek_for_encryption|high|Data Protection|custom|azure|Configure customer-managed keys for encrypting Azure Service Bus data at rest|SERVICE_BUS|CSE-PC-AZURE-SERVICEBUS-13121|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#customer_managed_key-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SERVICEBUS-13122"]="1.31.2.2|1.31.2|service_bus_namespace_is_not_using_tls_version_1_2_or_higher|high|Data Protection|custom|azure|Service Bus Namespace should use TLS version 1.2 or higher to ensure secure communication.|SERVICE_BUS|CSE-PC-AZURE-SERVICEBUS-13122|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#minimum_tls_version-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SERVICEBUS-13132"]="1.31.3.2|1.31.3|service_bus_namespace_is_not_using_premium_sku|critical|Network Security|custom|azure|Azure ServiceBus Namespace must be using premium SKU|SERVICE_BUS|CSE-PC-AZURE-SERVICEBUS-13132|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SERVICEBUS-13133"]="1.31.3.3|1.31.3|service_bus_namespace_have_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure ServiceBus Namespace|SERVICE_BUS|CSE-PC-AZURE-SERVICEBUS-13133|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#sku-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SERVICEBUS-13151"]="1.31.5.1|1.31.5|service_bus_namespace_is_missing_mandatory_tags|low|Governance|custom|azure|IT Hygiene: �Azure Service Bus must be tagged per standards|SERVICE_BUS|CSE-PC-AZURE-SERVICEBUS-13151|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-DATABRICKS-11121"]="1.11.2.1|1.11.2|data_bricks_workspace_not_using_cmek_for_encryption|high|Data Protection|custom|azure|Encryption at-rest: Use customer managed keys (CMK) to comply with CVS encryption standards|DATA_BRICKS|CSE-PC-AZURE-DATABRICKS-11121|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace.html#customer_managed_key_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-DATABRICKS-11131"]="1.11.3.1|1.11.3|data_bricks_workspace_public_network_access_is_enabled|critical|Network Security|custom|azure|Disable public access to Azure Databricks|DATA_BRICKS|CSE-PC-AZURE-DATABRICKS-11131|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-DATABRICKS-11133"]="1.11.3.3|1.11.3|data_bricks_with_cluster_connectivity_is_using_public_ip|critical|Network Security|custom|azure|Deploy Azure Databricks workspace with Secure Cluster Connectivity (No Public IP)|DATA_BRICKS|CSE-PC-AZURE-DATABRICKS-11133|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace.html#no_public_ip-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-DATABRICKS-11151"]="1.11.5.1|1.11.5|data_bricks_workspace_is_missing_manadatory_tags|low|Governance|custom|azure|IT Hygiene:  Azure Databricks must be tagged per standards|DATA_BRICKS|CSE-PC-AZURE-DATABRICKS-11151|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SEARCHSERVICE-16214"]="1.62.1.4|1.62.1|search_service_have_local_authentication_enabled|high|IAM Protection|custom|azure|Azure Search Service must have local authentication enabled|SEARCH_SERVICE|CSE-PC-AZURE-SEARCHSERVICE-16214|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/search_service.html#local_authentication_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SEARCHSERVICE-16223"]="1.62.2.3|1.62.2|search_service_is_not_enforcing_cmek_for_encryption|high|Data Protection|custom|azure|Enforce customer managed key for encryption in Azure Search Service|SEARCH_SERVICE|CSE-PC-AZURE-SEARCHSERVICE-16223|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/search_service.html#customer_managed_key_enforcement_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SEARCHSERVICE-16231"]="1.62.3.1|1.62.3|search_service_have_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure Search Service|SEARCH_SERVICE|CSE-PC-AZURE-SEARCHSERVICE-16231|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/search_service.html#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SEARCHSERVICE-16251"]="1.62.5.1|1.62.5|search_service_is_missing_mandatory_tags|low|Governance|custom|azure|IT Hygiene: Azure Search Service must be tagged per standards|SEARCH_SERVICE|CSE-PC-AZURE-SEARCHSERVICE-16251|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/search_service.html#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-LANGUAGESERVICE-17314"]="1.73.1.4|1.73.1|azure_ai_language_service_has_local_authentication_enabled|high|IAM Protection|custom|azure|Azure AI Language Service must have local authentication disabled|AI Language Service|CSE-PC-AZURE-LANGUAGESERVICE-17314|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-LANGUAGESERVICE-17323"]="1.73.2.3|1.73.2|azure_ai_language_service_not_configured_with_cmek|high|Data Protection|custom|azure|Enforce customer managed key for encryption in Azure AI Language Service|AI Language Service|CSE-PC-AZURE-LANGUAGESERVICE-17323|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#customer_managed_key-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-LANGUAGESERVICE-17331"]="1.73.3.1|1.73.3|azure_ai_language_service_has_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure AI Language Service|AI Language Service|CSE-PC-AZURE-LANGUAGESERVICE-17331|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-LANGUAGESERVICE-17351"]="1.73.5.1|1.73.5|azure_ai_language_service_is_missing_required_tags|low|Governance|custom|azure|IT Hygiene: Azure AI Language Service must be tagged per standards|AI Language Service|CSE-PC-AZURE-LANGUAGESERVICE-17351|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SPEECHSERVICE-17714"]="1.77.1.4|1.77.1|azure_ai_speech_service_has_local_authentication_enabled|high|IAM Protection|custom|azure|Azure AI Speech Service must have local authentication disabled|AI Speech Service|CSE-PC-AZURE-SPEECHSERVICE-17714|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SPEECHSERVICE-17723"]="1.77.2.3|1.77.2|azure_ai_speech_service_not_configured_with_cmek|high|Data Protection|custom|azure|Enforce customer managed key for encryption in Azure AI Speech Service|AI Speech Service|CSE-PC-AZURE-SPEECHSERVICE-17723|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#customer_managed_key-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SPEECHSERVICE-17731"]="1.77.3.1|1.77.3|azure_ai_speech_service_has_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure AI Speech Service|AI Speech Service|CSE-PC-AZURE-SPEECHSERVICE-17731|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SPEECHSERVICE-17751"]="1.77.5.1|1.77.5|azure_ai_speech_service_is_missing_required_tags|low|Governance|custom|azure|IT Hygiene: Azure AI Speech Service must be tagged per standards|AI Speech Service|CSE-PC-AZURE-SPEECHSERVICE-17751|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-TRANSLATION-18014"]="1.80.1.4|1.80.1|azure_ai_translation_service_has_local_authentication_enabled|high|IAM Protection|custom|azure|Azure AI Translation Service must have local authentication disabled|AI Translation Service|CSE-PC-AZURE-TRANSLATION-18014|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-TRANSLATION-18023"]="1.80.2.3|1.80.2|azure_ai_translation_service_not_configured_with_cmek|high|Data Protection|custom|azure|Enforce customer managed key for encryption in Azure AI Translation Service|AI Translation Service|CSE-PC-AZURE-TRANSLATION-18023|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#customer_managed_key-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-TRANSLATION-18031"]="1.80.3.1|1.80.3|azure_ai_translation_service_has_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure AI Transaltion Service|AI Translation Service|CSE-PC-AZURE-TRANSLATION-18031|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-TRANSLATION-18051"]="1.80.5.1|1.80.5|azure_ai_translation_service_is_missing_required_tags|low|Governance|custom|azure|IT Hygiene: Azure AI Translation Service must be tagged per standards|AI Translation Service|CSE-PC-AZURE-TRANSLATION-18051|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-COMPUTERVISION-16714"]="1.67.1.4|1.67.1|azure_ai_computer_vision_service_has_local_authentication_enabled|high|IAM Protection|custom|azure|Azure AI Computer Vision Service must have local authentication disabled|AI Computer Vision|CSE-PC-AZURE-COMPUTERVISION-16714|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-COMPUTERVISION-16723"]="1.67.2.3|1.67.2|azure_ai_computer_vision_service_not_configured_with_cmek|high|Data Protection|custom|azure|Enforce customer managed key for encryption in Azure AI Computer Vision Service|AI Computer Vision|CSE-PC-AZURE-COMPUTERVISION-16723|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#customer_managed_key-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-COMPUTERVISION-16731"]="1.67.3.1|1.67.3|azure_ai_computer_vision_service_has_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure AI Computer Vision Service|AI Computer Vision|CSE-PC-AZURE-COMPUTERVISION-16731|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-COMPUTERVISION-16751"]="1.67.5.1|1.67.5|azure_ai_computer_vision_service_is_missing_required_tags|low|Governance|custom|azure|IT Hygiene: Azure AI Computer Vision Service must be tagged per standards|AI Computer Vision|CSE-PC-AZURE-COMPUTERVISION-16751|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-CONTENTSAFETY-17814"]="1.78.1.4|1.78.1|azure_ai_contentsafety_service_has_local_authentication_enabled|high|IAM Protection|custom|azure|Azure AI ContentSafety Service must have local authentication disabled|AI Content Safety|CSE-PC-AZURE-CONTENTSAFETY-17814|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-CONTENTSAFETY-17823"]="1.78.2.3|1.78.2|azure_ai_contentsafety_service_not_configured_with_cmek|high|Data Protection|custom|azure|Enforce customer managed key for encryption in Azure AI ContentSafety Service|AI Content Safety|CSE-PC-AZURE-CONTENTSAFETY-17823|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#customer_managed_key-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-CONTENTSAFETY-17831"]="1.78.3.1|1.78.3|azure_ai_contentsafety_service_has_public_network_access_enabled|critical|Network Security|custom|azure|Disable public access to Azure AI ContentSafety Service|AI Content Safety|CSE-PC-AZURE-CONTENTSAFETY-17831|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#public_network_access_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-CONTENTSAFETY-17851"]="1.78.5.1|1.78.5|azure_ai_contentsafety_service_is_missing_required_tags|low|Governance|custom|azure|IT Hygiene: Azure AI ContentSafety Service must be tagged per standards|AI Content Safety|CSE-PC-AZURE-CONTENTSAFETY-17851|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-AKS-11312"]="1.13.1.2|1.13.1|aks_cluster_authentication_must_set_to_rbac|high|IAM Protection|custom|azure|Azure Kubernetes Service Authentication must set to Azure RBAC|AKS|CSE-PC-AZURE-AKS-11312|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#role_based_access_control_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-AKS-11319"]="1.13.1.9|1.13.1|aks_cluster_local_accounts_must_be_disabled|high|IAM Protection|custom|azure|Kubernetes Local Accounts must be disabled|AKS|CSE-PC-AZURE-AKS-11319|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#local_account_disabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-AKS-11323"]="1.13.2.3|1.13.2|aks_cluster_storage_disk_must_be_encrypted_with_cmek|high|Data Protection|custom|azure|Azure Kubernetes Service cluster storage disks and all agent nodes at host must be encrypted using Customer managed encryption key.|AKS|CSE-PC-AZURE-AKS-11323|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#disk_encryption_set_id-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-AKS-11324"]="1.13.2.4|1.13.2|aks_cluster_must_encrypted_with_kms|high|Data Protection|custom|azure|Key Management Service (KMS v2) etcd encryption must be implemented to an Azure Kubernetes Service (AKS) cluster|AKS|CSE-PC-AZURE-AKS-11324|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#key_management_service-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-AKS-11332"]="1.13.3.2|1.13.3|aks_cluster_public_fqdn_must_be_disabled|critical|Network Security|custom|azure|AKS Cluster public FQDN must be disabled|AKS|CSE-PC-AZURE-AKS-11332|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#private_cluster_public_fqdn_enabled-1"

#CSE_AZURE_RULES_HASH -End  ---- Generated Code Don't Modify


             declare -A CSE_AZURE_CVSID_UUID_HASH
         


#CSE_AZURE_CVSID_UUID_HASH  -Start  ---- Generated Code Don't Modify

             CSE_AZURE_CVSID_UUID_HASH["1.31.1.4"]="CSE-PC-AZURE-SERVICEBUS-13114|service_bus_namespace_have_local_auth_enabled|SERVICE_BUS|Azure Service Bus must have local auth disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.31.2.1"]="CSE-PC-AZURE-SERVICEBUS-13121|service_bus_namespace_is_not_using_cmek_for_encryption|SERVICE_BUS|Configure customer-managed keys for encrypting Azure Service Bus data at rest"
            CSE_AZURE_CVSID_UUID_HASH["1.31.2.2"]="CSE-PC-AZURE-SERVICEBUS-13122|service_bus_namespace_is_not_using_tls_version_1_2_or_higher|SERVICE_BUS|Service Bus Namespace should use TLS version 1.2 or higher to ensure secure communication."
            CSE_AZURE_CVSID_UUID_HASH["1.31.3.2"]="CSE-PC-AZURE-SERVICEBUS-13132|service_bus_namespace_is_not_using_premium_sku|SERVICE_BUS|Azure ServiceBus Namespace must be using premium SKU"
            CSE_AZURE_CVSID_UUID_HASH["1.31.3.3"]="CSE-PC-AZURE-SERVICEBUS-13133|service_bus_namespace_have_public_network_access_enabled|SERVICE_BUS|Disable public access to Azure ServiceBus Namespace"
            CSE_AZURE_CVSID_UUID_HASH["1.31.5.1"]="CSE-PC-AZURE-SERVICEBUS-13151|service_bus_namespace_is_missing_mandatory_tags|SERVICE_BUS|IT Hygiene: �Azure Service Bus must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.11.2.1"]="CSE-PC-AZURE-DATABRICKS-11121|data_bricks_workspace_not_using_cmek_for_encryption|DATA_BRICKS|Encryption at-rest: Use customer managed keys (CMK) to comply with CVS encryption standards"
            CSE_AZURE_CVSID_UUID_HASH["1.11.3.1"]="CSE-PC-AZURE-DATABRICKS-11131|data_bricks_workspace_public_network_access_is_enabled|DATA_BRICKS|Disable public access to Azure Databricks"
            CSE_AZURE_CVSID_UUID_HASH["1.11.3.3"]="CSE-PC-AZURE-DATABRICKS-11133|data_bricks_with_cluster_connectivity_is_using_public_ip|DATA_BRICKS|Deploy Azure Databricks workspace with Secure Cluster Connectivity (No Public IP)"
            CSE_AZURE_CVSID_UUID_HASH["1.11.5.1"]="CSE-PC-AZURE-DATABRICKS-11151|data_bricks_workspace_is_missing_manadatory_tags|DATA_BRICKS|IT Hygiene:  Azure Databricks must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.62.1.4"]="CSE-PC-AZURE-SEARCHSERVICE-16214|search_service_have_local_authentication_enabled|SEARCH_SERVICE|Azure Search Service must have local authentication enabled"
            CSE_AZURE_CVSID_UUID_HASH["1.62.2.3"]="CSE-PC-AZURE-SEARCHSERVICE-16223|search_service_is_not_enforcing_cmek_for_encryption|SEARCH_SERVICE|Enforce customer managed key for encryption in Azure Search Service"
            CSE_AZURE_CVSID_UUID_HASH["1.62.3.1"]="CSE-PC-AZURE-SEARCHSERVICE-16231|search_service_have_public_network_access_enabled|SEARCH_SERVICE|Disable public access to Azure Search Service"
            CSE_AZURE_CVSID_UUID_HASH["1.62.5.1"]="CSE-PC-AZURE-SEARCHSERVICE-16251|search_service_is_missing_mandatory_tags|SEARCH_SERVICE|IT Hygiene: Azure Search Service must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.73.1.4"]="CSE-PC-AZURE-LANGUAGESERVICE-17314|azure_ai_language_service_has_local_authentication_enabled|AI Language Service|Azure AI Language Service must have local authentication disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.73.2.3"]="CSE-PC-AZURE-LANGUAGESERVICE-17323|azure_ai_language_service_not_configured_with_cmek|AI Language Service|Enforce customer managed key for encryption in Azure AI Language Service"
            CSE_AZURE_CVSID_UUID_HASH["1.73.3.1"]="CSE-PC-AZURE-LANGUAGESERVICE-17331|azure_ai_language_service_has_public_network_access_enabled|AI Language Service|Disable public access to Azure AI Language Service"
            CSE_AZURE_CVSID_UUID_HASH["1.73.5.1"]="CSE-PC-AZURE-LANGUAGESERVICE-17351|azure_ai_language_service_is_missing_required_tags|AI Language Service|IT Hygiene: Azure AI Language Service must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.77.1.4"]="CSE-PC-AZURE-SPEECHSERVICE-17714|azure_ai_speech_service_has_local_authentication_enabled|AI Speech Service|Azure AI Speech Service must have local authentication disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.77.2.3"]="CSE-PC-AZURE-SPEECHSERVICE-17723|azure_ai_speech_service_not_configured_with_cmek|AI Speech Service|Enforce customer managed key for encryption in Azure AI Speech Service"
            CSE_AZURE_CVSID_UUID_HASH["1.77.3.1"]="CSE-PC-AZURE-SPEECHSERVICE-17731|azure_ai_speech_service_has_public_network_access_enabled|AI Speech Service|Disable public access to Azure AI Speech Service"
            CSE_AZURE_CVSID_UUID_HASH["1.77.5.1"]="CSE-PC-AZURE-SPEECHSERVICE-17751|azure_ai_speech_service_is_missing_required_tags|AI Speech Service|IT Hygiene: Azure AI Speech Service must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.80.1.4"]="CSE-PC-AZURE-TRANSLATION-18014|azure_ai_translation_service_has_local_authentication_enabled|AI Translation Service|Azure AI Translation Service must have local authentication disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.80.2.3"]="CSE-PC-AZURE-TRANSLATION-18023|azure_ai_translation_service_not_configured_with_cmek|AI Translation Service|Enforce customer managed key for encryption in Azure AI Translation Service"
            CSE_AZURE_CVSID_UUID_HASH["1.80.3.1"]="CSE-PC-AZURE-TRANSLATION-18031|azure_ai_translation_service_has_public_network_access_enabled|AI Translation Service|Disable public access to Azure AI Transaltion Service"
            CSE_AZURE_CVSID_UUID_HASH["1.80.5.1"]="CSE-PC-AZURE-TRANSLATION-18051|azure_ai_translation_service_is_missing_required_tags|AI Translation Service|IT Hygiene: Azure AI Translation Service must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.67.1.4"]="CSE-PC-AZURE-COMPUTERVISION-16714|azure_ai_computer_vision_service_has_local_authentication_enabled|AI Computer Vision|Azure AI Computer Vision Service must have local authentication disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.67.2.3"]="CSE-PC-AZURE-COMPUTERVISION-16723|azure_ai_computer_vision_service_not_configured_with_cmek|AI Computer Vision|Enforce customer managed key for encryption in Azure AI Computer Vision Service"
            CSE_AZURE_CVSID_UUID_HASH["1.67.3.1"]="CSE-PC-AZURE-COMPUTERVISION-16731|azure_ai_computer_vision_service_has_public_network_access_enabled|AI Computer Vision|Disable public access to Azure AI Computer Vision Service"
            CSE_AZURE_CVSID_UUID_HASH["1.67.5.1"]="CSE-PC-AZURE-COMPUTERVISION-16751|azure_ai_computer_vision_service_is_missing_required_tags|AI Computer Vision|IT Hygiene: Azure AI Computer Vision Service must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.78.1.4"]="CSE-PC-AZURE-CONTENTSAFETY-17814|azure_ai_contentsafety_service_has_local_authentication_enabled|AI Content Safety|Azure AI ContentSafety Service must have local authentication disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.78.2.3"]="CSE-PC-AZURE-CONTENTSAFETY-17823|azure_ai_contentsafety_service_not_configured_with_cmek|AI Content Safety|Enforce customer managed key for encryption in Azure AI ContentSafety Service"
            CSE_AZURE_CVSID_UUID_HASH["1.78.3.1"]="CSE-PC-AZURE-CONTENTSAFETY-17831|azure_ai_contentsafety_service_has_public_network_access_enabled|AI Content Safety|Disable public access to Azure AI ContentSafety Service"
            CSE_AZURE_CVSID_UUID_HASH["1.78.5.1"]="CSE-PC-AZURE-CONTENTSAFETY-17851|azure_ai_contentsafety_service_is_missing_required_tags|AI Content Safety|IT Hygiene: Azure AI ContentSafety Service must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.13.1.2"]="CSE-PC-AZURE-AKS-11312|aks_cluster_authentication_must_set_to_rbac|AKS|Azure Kubernetes Service Authentication must set to Azure RBAC"
            CSE_AZURE_CVSID_UUID_HASH["1.13.1.9"]="CSE-PC-AZURE-AKS-11319|aks_cluster_local_accounts_must_be_disabled|AKS|Kubernetes Local Accounts must be disabled"
            CSE_AZURE_CVSID_UUID_HASH["1.13.2.3"]="CSE-PC-AZURE-AKS-11323|aks_cluster_storage_disk_must_be_encrypted_with_cmek|AKS|Azure Kubernetes Service cluster storage disks and all agent nodes at host must be encrypted using Customer managed encryption key."
            CSE_AZURE_CVSID_UUID_HASH["1.13.2.4"]="CSE-PC-AZURE-AKS-11324|aks_cluster_must_encrypted_with_kms|AKS|Key Management Service (KMS v2) etcd encryption must be implemented to an Azure Kubernetes Service (AKS) cluster"
            CSE_AZURE_CVSID_UUID_HASH["1.13.3.2"]="CSE-PC-AZURE-AKS-11332|aks_cluster_public_fqdn_must_be_disabled|AKS|AKS Cluster public FQDN must be disabled"

#CSE_AZURE_CVSID_UUID_HASH  -End  ---- Generated Code Don't Modify
