#!/usr/bin/env sh


             declare -A CSE_AZURE_RULES_HASH


#CSE_AZURE_RULES_HASH -Start  ---- Generated Code Don't Modify

             CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11611"]="1.16.1.1|1.16.1|sql_server_has_only_read_authentication_for_admin|high|IAM|custom|azure|In Azure Portal - Azure SQL Server - Settings - Microsoft Entra ID|SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11611|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_active_directory_administrator"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11614"]="1.16.1.4|1.16.1|sql_server_is_not_enabled_with_managed_identity|high|IAM|custom|azure|In Azure Portal - Azure SQL Server - Settings - Remove Admin|SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11614|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server#identity_ids"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11621"]="1.16.2.1|1.16.2|sql_server_is_not_configured_with_cmek_for_transparent_data_encryption|high|Data Protection|custom|azure|In Azure Portal - Azure SQL Server - Security - Transparent data encryption - set Customer-managed key|SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11621|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server_transparent_data_encryption"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11622"]="1.16.2.2|1.16.2|sql_db_is_not_configured_with_cmek_for_transparent_data_encryption|high|Data Protection|custom|azure|In Azure Portal - Azure SQL database - Security - Data Encryption - set On -Enabled CMK |SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11622|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database#transparent_data_encryption_enabled"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11623"]="1.16.2.3|1.16.2|sql_server_is_not_configured_with_tls_1_2|low|Data Protection|custom|azure|In Azure Portal - Azure SQL Server - Security - Identity - Enable managed identity on.|SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11623|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server#minimum_tls_version"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11631"]="1.16.3.1|1.16.3|sql_server_is_not_configured_with_private_endpoint|critical|Network Security Controls|custom|azure|In Azure Portal - Azure SQL Server - Security - Networking - Private access - Create private endpoint|SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11631|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-SQLSERVER-11651"]="1.16.5.1|1.16.5|sql_server_must_be_tagged_as_per_standards|low|Governance|custom|azure|Following standard tags must be present - ITPMID ; Environmenttype ; Sharedemailaddress; Costcenter; Dataclassification|SQL_SERVER|CSE-PC-AZURE-SQLSERVER-11651|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server#tags"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13552"]="1.35.5.2|1.35.5|app_gateway_is_not_using_v2_sku|high|Governance|custom|azure|Only Private App gateway V2 has to be used|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13552|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#sku"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13522"]="1.35.2.2|1.35.2|app_gateway_is_not_using_tls_v1_2_or_higher|high|Data Protection|custom|azure|Configure minimum required version of Transport Layer Security|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13522|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#disabled_protocols"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13551"]="1.35.5.1|1.35.5|app_gateway_is_missing_tags|low|Governance|custom|azure|IT Hygiene:Function must be tagged per standards|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13551|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#tags"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13521"]="1.35.2.1|1.35.2|app_gateway_is_not_using_https_for_encryption|high|Data Protection|custom|azure|Ensure data is encrypted during transit from and to the App gateway|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13521|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#backend_http_settings_name"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13531"]="1.35.3.1|1.35.3|app_gateway_is_not_using_private_ip_for_frontend_configuration|high|Network Security|custom|azure|Use Private IP address only frontend IP configuration|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13531|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#private_ip_address"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13538"]="1.35.3.8|1.35.3|app_gateway_does_not_have_waf_enabled|low|Network Security|custom|azure|Azure Application Gateway does not have the Web application firewall enabled|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13538|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#waf_configuration"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-13539"]="1.35.3.9|1.35.3|app_gateway_waf_policy_is_not_enabled_for_prevention_mode|low|Network Security|custom|azure|Azure Application Gateway WAF Policy is not enabled for Prevention mode|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-13539|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#firewall_mode"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPGATEWAY-135310"]="1.35.3.10|1.35.3|app_gateway_waf_policy_rule_for_remote_execution_is_not_enabled|low|Network Security|custom|azure|Azure Application Gateway WAF policy rule for remote execution is not enabled|APPGATEWAY|CSE-PC-AZURE-APPGATEWAY-135310|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy#enabled"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPCONFIGURATION-1632"]="1.6.3.2|1.6.3|app_configuration_access_is_not_limited_to_private_endpoint|critical|Network Security|custom|azure|Limit access through private endpoint|APP_CONFIGURATION|CSE-PC-AZURE-APPCONFIGURATION-1632|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPCONFIGURATION-1651"]="1.6.5.1|1.6.5|app_configuration_is_missing_tags|low|Governance|custom|azure|IT Hygiene App Configuration must be tagged per standards|APP_CONFIGURATION|CSE-PC-AZURE-APPCONFIGURATION-1651|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration#tags-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPCONFIGURATION-1614"]="1.6.1.4|1.6.1|app_configuration_is_using_local_authentication|high|IAM|custom|azure|App Configuration Using Local Authentication|APP_CONFIGURATION|CSE-PC-AZURE-APPCONFIGURATION-1614|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration#local_auth_enabled-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPCONFIGURATION-1631"]="1.6.3.1|1.6.3|app_configuration_public_network_access_is_enabled|critical|Network Security|custom|azure|Disable public access to Azure App Configuration|APP_CONFIGURATION|CSE-PC-AZURE-APPCONFIGURATION-1631|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration#public_network_access-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPCONFIGURATION-1652"]="1.6.5.2|1.6.5|app_configuration_sku_is_using_free_tier|medium|Governance|custom|azure|Free tier is not allowed|APP_CONFIGURATION|CSE-PC-AZURE-APPCONFIGURATION-1652|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration#sku-1"
            CSE_AZURE_RULES_HASH["CSE-PC-AZURE-APPCONFIGURATION-1621"]="1.6.2.1|1.6.2|app_configuration_is_not_encrypted_data_at_rest_in_transit|high|Data Protection|custom|azure|Data is encrypted during transit from to the Azure App Configuration|APP_CONFIGURATION|CSE-PC-AZURE-APPCONFIGURATION-1621|https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration#encryption-1"

#CSE_AZURE_RULES_HASH -End  ---- Generated Code Don't Modify


             declare -A CSE_AZURE_CVSID_UUID_HASH
         


#CSE_AZURE_CVSID_UUID_HASH  -Start  ---- Generated Code Don't Modify

             CSE_AZURE_CVSID_UUID_HASH["1.16.1.1"]="CSE-PC-AZURE-SQLSERVER-11611|sql_server_has_only_read_authentication_for_admin|SQL_SERVER|In Azure Portal - Azure SQL Server - Settings - Microsoft Entra ID"
            CSE_AZURE_CVSID_UUID_HASH["1.16.1.4"]="CSE-PC-AZURE-SQLSERVER-11614|sql_server_is_not_enabled_with_managed_identity|SQL_SERVER|In Azure Portal - Azure SQL Server - Settings - Remove Admin"
            CSE_AZURE_CVSID_UUID_HASH["1.16.2.1"]="CSE-PC-AZURE-SQLSERVER-11621|sql_server_is_not_configured_with_cmek_for_transparent_data_encryption|SQL_SERVER|In Azure Portal - Azure SQL Server - Security - Transparent data encryption - set Customer-managed key"
            CSE_AZURE_CVSID_UUID_HASH["1.16.2.2"]="CSE-PC-AZURE-SQLSERVER-11622|sql_db_is_not_configured_with_cmek_for_transparent_data_encryption|SQL_SERVER|In Azure Portal - Azure SQL database - Security - Data Encryption - set On -Enabled CMK "
            CSE_AZURE_CVSID_UUID_HASH["1.16.2.3"]="CSE-PC-AZURE-SQLSERVER-11623|sql_server_is_not_configured_with_tls_1_2|SQL_SERVER|In Azure Portal - Azure SQL Server - Security - Identity - Enable managed identity on."
            CSE_AZURE_CVSID_UUID_HASH["1.16.3.1"]="CSE-PC-AZURE-SQLSERVER-11631|sql_server_is_not_configured_with_private_endpoint|SQL_SERVER|In Azure Portal - Azure SQL Server - Security - Networking - Private access - Create private endpoint"
            CSE_AZURE_CVSID_UUID_HASH["1.16.5.1"]="CSE-PC-AZURE-SQLSERVER-11651|sql_server_must_be_tagged_as_per_standards|SQL_SERVER|Following standard tags must be present - ITPMID ; Environmenttype ; Sharedemailaddress; Costcenter; Dataclassification"
            CSE_AZURE_CVSID_UUID_HASH["1.35.5.2"]="CSE-PC-AZURE-APPGATEWAY-13552|app_gateway_is_not_using_v2_sku|APPGATEWAY|Only Private App gateway V2 has to be used"
            CSE_AZURE_CVSID_UUID_HASH["1.35.2.2"]="CSE-PC-AZURE-APPGATEWAY-13522|app_gateway_is_not_using_tls_v1_2_or_higher|APPGATEWAY|Configure minimum required version of Transport Layer Security"
            CSE_AZURE_CVSID_UUID_HASH["1.35.5.1"]="CSE-PC-AZURE-APPGATEWAY-13551|app_gateway_is_missing_tags|APPGATEWAY|IT Hygiene:Function must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.35.2.1"]="CSE-PC-AZURE-APPGATEWAY-13521|app_gateway_is_not_using_https_for_encryption|APPGATEWAY|Ensure data is encrypted during transit from and to the App gateway"
            CSE_AZURE_CVSID_UUID_HASH["1.35.3.1"]="CSE-PC-AZURE-APPGATEWAY-13531|app_gateway_is_not_using_private_ip_for_frontend_configuration|APPGATEWAY|Use Private IP address only frontend IP configuration"
            CSE_AZURE_CVSID_UUID_HASH["1.35.3.8"]="CSE-PC-AZURE-APPGATEWAY-13538|app_gateway_does_not_have_waf_enabled|APPGATEWAY|Azure Application Gateway does not have the Web application firewall enabled"
            CSE_AZURE_CVSID_UUID_HASH["1.35.3.9"]="CSE-PC-AZURE-APPGATEWAY-13539|app_gateway_waf_policy_is_not_enabled_for_prevention_mode|APPGATEWAY|Azure Application Gateway WAF Policy is not enabled for Prevention mode"
            CSE_AZURE_CVSID_UUID_HASH["1.35.3.10"]="CSE-PC-AZURE-APPGATEWAY-135310|app_gateway_waf_policy_rule_for_remote_execution_is_not_enabled|APPGATEWAY|Azure Application Gateway WAF policy rule for remote execution is not enabled"
            CSE_AZURE_CVSID_UUID_HASH["1.6.3.2"]="CSE-PC-AZURE-APPCONFIGURATION-1632|app_configuration_access_is_not_limited_to_private_endpoint|APP_CONFIGURATION|Limit access through private endpoint"
            CSE_AZURE_CVSID_UUID_HASH["1.6.5.1"]="CSE-PC-AZURE-APPCONFIGURATION-1651|app_configuration_is_missing_tags|APP_CONFIGURATION|IT Hygiene App Configuration must be tagged per standards"
            CSE_AZURE_CVSID_UUID_HASH["1.6.1.4"]="CSE-PC-AZURE-APPCONFIGURATION-1614|app_configuration_is_using_local_authentication|APP_CONFIGURATION|App Configuration Using Local Authentication"
            CSE_AZURE_CVSID_UUID_HASH["1.6.3.1"]="CSE-PC-AZURE-APPCONFIGURATION-1631|app_configuration_public_network_access_is_enabled|APP_CONFIGURATION|Disable public access to Azure App Configuration"
            CSE_AZURE_CVSID_UUID_HASH["1.6.5.2"]="CSE-PC-AZURE-APPCONFIGURATION-1652|app_configuration_sku_is_using_free_tier|APP_CONFIGURATION|Free tier is not allowed"
            CSE_AZURE_CVSID_UUID_HASH["1.6.2.1"]="CSE-PC-AZURE-APPCONFIGURATION-1621|app_configuration_is_not_encrypted_data_at_rest_in_transit|APP_CONFIGURATION|Data is encrypted during transit from to the Azure App Configuration"

#CSE_AZURE_CVSID_UUID_HASH  -End  ---- Generated Code Don't Modify
